# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 80fe6ef32603061149b03a73d27a25ef040b2229d790e573632512ac9178b4aa9b9d6001e824f8756f856457c79f77d716085fdb9a3155524a0724ec3543f22f

test:
  secret_key_base: 5aa75b1b9b7fb26c5ec127bdf80894886ed91a135d8e7b00edea0323ea3d10ed1d28591a88609d6cb9daac9994bf9e397b64007aaa6f0424bea05486c8d35a9a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
